<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>prompt_capabilities</name>
  <version>0.2.0</version>
  <description>Provides capabilities2 runners for the Prompt Tools stack.</description>

  <maintainer email="kalanaratnayake95@gmail.com">Kalana Ratnayake</maintainer>
  <maintainer email="kalana.ratnayakemudiyanselage@canberra.edu.au">Kalana Ratnayake</maintainer>

  <author email="kalana.ratnayakemudiyanselage@canberra.edu.au">Kalana Ratnayake</author>
  <author email="kalanaratnayake95@gmail.com">Kalana Ratnayake</author>
  
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>pluginlib</depend>
  <depend>prompt_msgs</depend>
  <depend>capabilities2_msgs</depend>
  <depend>capabilities2_runner</depend>
  <depend>capabilities2_events</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>

    <!-- PromptLaunchRunner -->
    <!-- <capability_interface>
      interfaces/PromptLaunchRunner.yaml
    </capability_interface> -->

    <!-- <capability_provider>
      providers/PromptLaunchRunner.yaml
    </capability_provider> -->

    <!-- PromptTextRunner -->
    <capability_interface>
      interfaces/PromptTextRunner.yaml
    </capability_interface>

    <capability_provider>
      providers/PromptTextRunner.yaml
    </capability_provider>

    <!-- PromptPoseRunner -->
    <capability_interface>
      interfaces/PromptPoseRunner.yaml
    </capability_interface>

    <capability_provider>
      providers/PromptPoseRunner.yaml
    </capability_provider>

    <!-- PromptCurrentCartesianPoseRunner -->
    <capability_interface>
      interfaces/PromptCurrentCartesianPoseRunner.yaml
    </capability_interface>

    <capability_provider>
      providers/PromptCurrentCartesianPoseRunner.yaml
    </capability_provider>

    <!-- PromptCurrentJointPoseRunner -->
    <capability_interface>
      interfaces/PromptCurrentJointPoseRunner.yaml
    </capability_interface>

    <capability_provider>
      providers/PromptCurrentJointPoseRunner.yaml
    </capability_provider>

    <!-- PromptNamedPosesRunner -->
    <capability_interface>
      interfaces/PromptNamedPosesRunner.yaml
    </capability_interface>

    <capability_provider>
      providers/PromptNamedPosesRunner.yaml
    </capability_provider>

    <!-- PromptGripperStateRunner -->
    <capability_interface>
      interfaces/PromptGripperStateRunner.yaml
    </capability_interface>

    <capability_provider>
      providers/PromptGripperStateRunner.yaml
    </capability_provider>

    <!-- PromptSpeechRunner -->
    <capability_interface>
      interfaces/PromptSpeechRunner.yaml
    </capability_interface>

    <capability_provider>
      providers/PromptSpeechRunner.yaml
    </capability_provider>

  </export>
</package>
